<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
    public function totalClientes($precio)// $precio es donde indicaremos el importe
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.pedido', 'pedido')
            ->andWhere('pedido.precio = :precio')
            ->setParameter('precio', $precio)
            ->addOrderBy('p.precio', 'ASC')
            ->getQuery()
        ;
        return $qb;
    }
}