<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends EntityRepository
{
    public function totalPedidosById($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.cliente', 'cliente')
            ->andWhere('cliente.id = :id')
            ->setParameter('id', $id)
            ->addOrderBy('p.fecha', 'DESC')
            ->getQuery()
        ;
        return $qb;
    }
}
